Add method to anonymize candidates
pyoupyou/pyoupyou pull request #109
Opened 2020-10-08 09:11 UTC by meven

cc @bport

2020-10-08 09:31 UTC, bport requested changes

2020-10-08 09:31 UTC, bport commented on interview/models.py
> +        if len(self.phone) > 0:
`if self.phone:`

2020-10-08 09:31 UTC, bport commented on interview/tests.py
> +from pyoupyou.settings import SECRET_ANON_SALT
Do import from `from django.conf import settings` this will allow to change settings at django level

2020-10-08 09:31 UTC, bport commented on pyoupyou/settings/prod.py
> +SECRET_ANON_SALT = "production-salt-for-candidate-anonymization"
Don't put it in prod.py or people will forgot to change it.
Extend field needed in `settings/__init__.py` to warn administrator

2020-10-08 09:31 UTC, bport commented on interview/models.py
> +        return " ".encode("ascii").join(res)
Anonymize name without splitting it. We can imagine too many [sub] names, and result will not fit in 41 character digests.

2020-10-08 09:31 UTC, bport commented on interview/models.py
> +    anonymized_hashed_name = models.CharField(_("Anonymized Hashed Name"), max_length=41)
We can perhaps have hashed_email and hashed_phone too
and we can compute them on save. Script to anonymize will be only responsible to cleanup name/email/phone and document field then.

2020-10-08 09:53 UTC, meven commented on interview/models.py
> +    anonymized_hashed_name = models.CharField(_("Anonymized Hashed Name"), max_length=41)
I was thinking to run the anonymization through a Command python script like batch_update_state, that  would make this unnecessary

2020-10-08 14:11 UTC, bport commented on interview/models.py
> +        super(Candidate, self).save(*args, **kwargs)
I guess we want to update anonymized data only if anonymized is False

2020-11-12 08:57 UTC, bport commented on interview/models.py
> +import unicodedata
need to be top of file

2021-01-14 09:02 UTC, bport requested changes

2021-01-14 09:37 UTC, meven commented on interview/migrations/0014_candidate_anonymization.py
> +    from django.apps import apps
No in fact, this is not the same apps module.
The apps  returned by the framework rae Mock Models, importing `django.apps` allows to access the real models and the "real" save() method as defined in models.py, that is needed here.
See second warning in https://docs.djangoproject.com/en/3.1/topics/migrations/#historical-models

2021-01-14 09:46 UTC, meven commented on interview/management/commands/anonymize.py
> +            date.fromisoformat(options["date"]) if options["date"] else now().date() - relativedelta(months=6)
Made it 1 year, can add setting if needed by I doubt we will need to change this setting value compared to default.

2021-02-11 08:56 UTC, bport requested changes

2021-02-11 08:56 UTC, bport commented on interview/migrations/0014_candidate_anonymization.py
> +    from django.apps import apps
I think it will be better to duplicate code there to avoid problem in the future (if we change save implementation, the migration will use the new one)

2021-02-11 08:56 UTC, bport commented on interview/management/commands/anonymize.py
> +                proc.candidate.save()
We will end with empty name as hash in anonymized field I guess because firstly we clean up field and then we compute hash on the empty name.

2021-02-11 09:04 UTC, meven commented on interview/migrations/0014_candidate_anonymization.py
> +    from django.apps import apps
The migration is mostly a one-time thing, is it necessary then ?

2021-02-11 09:14 UTC, meven commented on interview/management/commands/anonymize.py
> +                proc.candidate.save()
Hashes are computed only in `Candidate.save` only when `Candidate.name` is not empty and `Candidate.anonymized` is False, which is set to true in `Candidate.anonymize`.
Or am I missing your point ?

2021-02-11 09:19 UTC, bport commented on interview/migrations/0014_candidate_anonymization.py
> +    from django.apps import apps
yes because for example if you init a new database in the future migration will be applied with a different save version or we can imagine people not migrating at expected time

2021-02-11 09:19 UTC, bport commented on interview/management/commands/anonymize.py
> +                proc.candidate.save()
My bad

2021-02-11 18:15 UTC, meven commented on interview/migrations/0014_candidate_anonymization.py
> +    from django.apps import apps
Would it be ok to call `Candidate.compute_anonymized_fields` explicitly instead ?
Duplicating the anonymization code is a bit involved.

2021-03-11 11:20 UTC, meven commented on interview/migrations/0014_candidate_anonymization.py
> +    from django.apps import apps
I did just that, hope that it is ok with you.

2021-03-11 14:10 UTC, bport requested changes

2021-03-11 14:10 UTC, bport commented on interview/views.py
> +                or duplicates.count() == 0
You can replace `duplicates is None or duplicates.count() == 0`
by
`not duplicates`

2021-03-11 14:10 UTC, bport commented on interview/views.py
> +            if past_candidate_id is not None:
You can simplify
if past_candidate_id is not None:
by
if past_candidate_id:

2021-03-11 14:10 UTC, bport commented on interview/views.py
> +                if duplicates.count() > 0:
if duplicates:

Allow to get queryset directly, if it's empty one request in both case but if we have data we need one query less

2021-06-10 07:03 UTC, bport requested changes

2021-06-10 07:03 UTC, bport commented on interview/migrations/0015_candidate_anonymization.py
> +        candidate.compute_anonymized_fields()
Duplicate code here to avoid future problem

2021-06-10 07:03 UTC, bport commented on interview/models.py
> +    anonymized_hashed_phone = models.CharField(_("Anonymized Hashed Phone"), max_length=41, blank=True)
Don't anonymize phone, a phone rainbow table is doable to easily

2021-06-10 07:03 UTC, bport commented on interview/models.py
> +            Document.objects.filter(candidate=self).delete()
Ensure document is deleted on disk too

2021-06-10 07:51 UTC, meven commented on interview/models.py
> +    anonymized_hashed_phone = models.CharField(_("Anonymized Hashed Phone"), max_length=41, blank=True)
So I can remove anonymized_hashed_phone field I guess.

2021-09-09 16:06 UTC, closed without merging

2021-09-09 16:08 UTC, ArnaudChirat commented
Has been merge with another PR
see commit e3fb12eaee8ee706a040cef7444cf3d2e6c0c8c2